/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing;

import dao.DaoPersonnel;
import dao.DaoService;
import dao.DaoSousService;
import dao.DaoTicket;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import metier.Personnel;
import metier.Service;
import metier.SousService;
import metier.Ticket;

/**
 *
 * @author Mehdi
 */
public class SuperviseurTicket extends JInternalFrame {

    /**
     * Creates new form SuperviseurTicket2
     */
    JDesktopPane d;
    public SuperviseurTicket(JDesktopPane d) {
        this.d=d;
        initComponents();
        DaoTicket daoT=new DaoTicket();
        List<Ticket> liste = daoT.selectAll();
        initialiserListeTicket(liste);
        
        //this.setSize(800, 400);
    }

    private void initialiserListeTicket(List<Ticket> liste) {
        
        dcListeTicket.addColumn("Numéro");
        dcListeTicket.addColumn("Intitulé");
        dcListeTicket.addColumn("Service");
        dcListeTicket.addColumn("Sous Service");

        dcListeTicket.addColumn("Etat Demande");

        dcListeTicket.addColumn("date Demande");
        dcListeTicket.addColumn("date Traitement");
        dcListeTicket.addColumn("Priorité");
        dcListeTicket.addColumn("Affectation");
        dcListeTicket.addColumn("Tickets Attribué");
       

        this.jTableListeTicket.setModel(dcListeTicket);
        personnel = jTableListeTicket.getColumnModel().getColumn(8);
     
      
        DaoPersonnel daoP = new DaoPersonnel();
        List<Personnel> listPersonnel = daoP.selectAll();

        DaoTicket daoT = new DaoTicket();
    
        

        DaoSousService daoSs = new DaoSousService();
        DaoService daoS = new DaoService();

    
        
        for (int j = 0; j < liste.size(); j++) {
            //Ticket ticket = (Ticket) o;
            SousService ss = daoSs.selectById(liste.get(j).getSousService().getId());
            Service s = daoS.selectById(ss.getIdService());
            List<Integer> idService;

     
            
         JComboBox comboBox = new JComboBox();
             //comboBox.removeAllItems();
            personnel.setCellEditor(new DefaultCellEditor(comboBox));
            
            for (int i = 0; i < listPersonnel.size(); i++) {

                if (listPersonnel.get(i).getIdService() == s.getId()) {
                    
                   
                    comboBox.addItem("");
                    
                } 

            }
                   
           /* for (int i = 0; i < comboBox.getItemCount(); i++) {
                System.out.println(i + " " +personnel.getCellEditor().getCellEditorValue());
            }*/
            this.dcListeTicket.addRow(new Object[]{liste.get(j).getId(),liste.get(j).getTitreDemande(), s.getService(), ss.getNom(), liste.get(j).getEtatDemande(), liste.get(j).getDateCreation(), liste.get(j).getDateEstimee(), liste.get(j).getPriorite(), personnel.getCellEditor().getCellEditorValue()});
          // System.out.println(this.dcListeTicket.getRowCount());
            this.jTableListeTicket.setModel(dcListeTicket);
            
        }
         sorter= new TableRowSorter<TableModel>(dcListeTicket);
         jTableListeTicket.setRowSorter(sorter);

         // jTableListeTicket.setAutoResizeMode(jTableListeTicket.AUTO_RESIZE_ALL_COLUMNS);
        //  jTableListeTicket.setSize(800, 1000);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeTicket = new javax.swing.JTable();
        jButtonAfficheTicket = new javax.swing.JButton();
        jFiltre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonMiseAjour = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTableListeTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableListeTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListeTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListeTicket);

        jButtonAfficheTicket.setText("Afficher Ticket");
        jButtonAfficheTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficheTicketActionPerformed(evt);
            }
        });

        jFiltre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFiltreKeyTyped(evt);
            }
        });

        jLabel1.setText("Filtre");

        jButtonMiseAjour.setText("Mise à jour");
        jButtonMiseAjour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMiseAjourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jButtonAfficheTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButtonMiseAjour, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAfficheTicket)
                    .addComponent(jFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonMiseAjour))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFiltreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFiltreKeyTyped
        // TODO add your handling code here:
        String text=jFiltre.getText().toLowerCase();
       
         if(text.length()==0){
             sorter.setRowFilter(null);
         }
                sorter.setRowFilter(RowFilter.regexFilter(text));
    }//GEN-LAST:event_jFiltreKeyTyped

    private void jButtonAfficheTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficheTicketActionPerformed
        // TODO add your handling code here:
        int ligneselec = jTableListeTicket.getSelectedRow();
        DaoTicket daoT = new DaoTicket();
        List<Ticket> listeT=daoT.selectAll();
        for(int i=0;i<listeT.size();i++){
            if(listeT.get(i).getId()==(Integer) jTableListeTicket.getValueAt(ligneselec, 0)){
               VoirTicket ticketFenetre = new VoirTicket(listeT.get(i),d);
               ticketFenetre.setVisible(true);
                this.d.add(ticketFenetre);
                ticketFenetre.moveToFront();
            }
        }
    }//GEN-LAST:event_jButtonAfficheTicketActionPerformed

    private void jButtonMiseAjourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMiseAjourActionPerformed
        // TODO add your handling code here:
        int ligneselec = jTableListeTicket.getSelectedRow();
        System.out.println("ooook " + jTableListeTicket.getValueAt(ligneselec, 8));
        System.out.println(jTableListeTicket.getValueAt(ligneselec, 1));
        DaoPersonnel daoP = new DaoPersonnel();
        //récupération de l'objet Personnel selctionné dans la combobox
        Personnel p = (Personnel) personnel.getCellEditor().getCellEditorValue();
        DaoTicket daoT = new DaoTicket();
        Ticket ticket = daoT.selectByName((String) jTableListeTicket.getValueAt(ligneselec, 1));
        System.out.println("yooo" + ticket.getTitreDemande());
        ticket.setPersonnel(p);
        daoT.update(ticket);
        //System.out.println("yooo" + p.getNom());
    }//GEN-LAST:event_jButtonMiseAjourActionPerformed

    private void jTableListeTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListeTicketMouseClicked
        // TODO add your handling code here:
         int ligneselec = jTableListeTicket.getSelectedRow();
         
          JComboBox comboBox = new JComboBox();
         DaoSousService daoSs = new DaoSousService();
          DaoService daoS = new DaoService();
          SousService ss=daoSs.selectByName((String) this.dcListeTicket.getValueAt(ligneselec, 3));
         
          Service s=daoS.selectById(ss.getIdService());
         
           DaoPersonnel daoP = new DaoPersonnel();
        List<Personnel> listPersonnel = daoP.selectAll();
        personnel.setCellEditor(new DefaultCellEditor(comboBox));
          for (int i = 0; i < listPersonnel.size(); i++) {

                if (listPersonnel.get(i).getIdService() == s.getId()) {
                    
                   
                    comboBox.addItem(listPersonnel.get(i));
                    
                } 
          }
          this.dcListeTicket.setValueAt(personnel.getCellEditor(), ligneselec, 8);
            this.jTableListeTicket.setModel(dcListeTicket);
              
        //récupération de l'objet Personnel selctionné dans la combobox
   Personnel p = (Personnel) personnel.getCellEditor().getCellEditorValue();
      DaoTicket daoT = new DaoTicket();
      Ticket ticket = daoT.selectByName((String) jTableListeTicket.getValueAt(ligneselec, 1));
      ticket.setPersonnel(p);
   //   daoT.update(ticket);
   
    }//GEN-LAST:event_jTableListeTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperviseurTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperviseurTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperviseurTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperviseurTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SuperviseurTicket().setVisible(true);
            }
        });
    }
    
    
    private DefaultTableModel dcListeTicket = new DefaultTableModel();
    private TableColumn personnel = new TableColumn();

    private TableRowSorter<TableModel>sorter;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfficheTicket;
    private javax.swing.JButton jButtonMiseAjour;
    private javax.swing.JTextField jFiltre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListeTicket;
    // End of variables declaration//GEN-END:variables
}
